// ============================================================================
// TAP Test Filter — group-based test selection helper
// ============================================================================
//
// SCAFFOLDED BY TAP. Do not edit this file directly; it will be regenerated
// the next time you re-scaffold the project from the TAP UI.
//
// ─── What this file does ────────────────────────────────────────────────────
//
// When TAP runs your suite as part of an Automation Execution, it materialises
// a manifest at the path stored in the `TAP_TEST_FILTER` environment variable
// (by convention `.tap-execution.json` at the workspace root). The manifest is
// a JSON array of `{ file, title?, testCaseId? }` entries describing the
// exact set of tests resolved from the selected Automation Test Groups.
//
// Two layers of filtering then apply:
//
//   1. FILE-LEVEL — `playwright.config.ts` uses `testIgnore` to skip every
//      spec file that isn't in the manifest. This is the primary filter and
//      scales to thousands of specs because Playwright never loads excluded
//      files into memory.
//
//   2. TEST-LEVEL (this file) — when a single spec file contains multiple
//      `test()` blocks and you only want some of them to run, call
//      `skipIfNotInTapFilter()` from a `test.beforeEach` hook. Tests whose
//      titles aren't in the manifest are marked `test.skip()` at runtime.
//
// ─── When you DON'T need this ──────────────────────────────────────────────
//
// If every spec file contains a single test, or if you always want to run
// every test in any spec file that the manifest includes, you can ignore
// this file completely. The file-level `testIgnore` already gives you
// group-based execution.
//
// ─── When you DO want this ─────────────────────────────────────────────────
//
// Add it to spec files where you want individual `test()` blocks filtered:
//
//   import { test } from '@playwright/test';
//   import { skipIfNotInTapFilter } from '../utils/tap-test-filter';
//
//   test.beforeEach(({}, testInfo) => skipIfNotInTapFilter(testInfo));
//
//   test('smoke: login works',     async ({ page }) => { ... });
//   test('regression: edge case',  async ({ page }) => { ... });
//
// When TAP_TEST_FILTER is unset (e.g. you ran `npx playwright test` locally
// without TAP), the helper is a no-op and every test runs.
// ============================================================================

import fs from 'fs';
import path from 'path';
import type { TestInfo } from '@playwright/test';

interface TapManifestEntry {
  file: string;
  title?: string | null;
  testCaseId?: number | null;
}

interface ResolvedFilter {
  /** POSIX-style file paths included in the manifest. */
  files: Set<string>;
  /**
   * Test titles included in the manifest, keyed by normalised file path.
   *
   * A spec file appears in this map ONLY if at least one of its manifest
   * entries has a non-empty title. If a file is in the manifest with no
   * titles attached, every test in that file is allowed to run.
   */
  titlesByFile: Map<string, Set<string>>;
  /** Set of files for which title-level filtering is active. */
  filesWithTitleFilter: Set<string>;
}

let cachedFilter: ResolvedFilter | null | undefined;

function normaliseToPosix(p: string): string {
  return p.replace(/\\/g, '/').replace(/^\/+/, '');
}

/**
 * Lazily load and cache the TAP manifest. Returns `null` when the env var
 * is unset or the file is missing / malformed — in either case the helper
 * becomes a no-op and every test runs.
 */
function loadFilter(): ResolvedFilter | null {
  if (cachedFilter !== undefined) return cachedFilter;

  const filterPath = process.env.TAP_TEST_FILTER;
  if (!filterPath) {
    cachedFilter = null;
    return cachedFilter;
  }

  try {
    const raw = fs.readFileSync(filterPath, 'utf-8');
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) {
      console.warn(
        `[TAP] TAP_TEST_FILTER at ${filterPath} is not a JSON array — disabling per-test filter`,
      );
      cachedFilter = null;
      return cachedFilter;
    }

    const files = new Set<string>();
    const titlesByFile = new Map<string, Set<string>>();
    const filesWithTitleFilter = new Set<string>();

    for (const entryRaw of parsed) {
      const entry = entryRaw as TapManifestEntry;
      if (!entry || typeof entry.file !== 'string' || entry.file.length === 0) continue;
      const file = normaliseToPosix(entry.file);
      files.add(file);

      const title = typeof entry.title === 'string' ? entry.title.trim() : '';
      if (title.length === 0) continue;

      filesWithTitleFilter.add(file);
      let titles = titlesByFile.get(file);
      if (!titles) {
        titles = new Set<string>();
        titlesByFile.set(file, titles);
      }
      titles.add(title);
    }

    cachedFilter = { files, titlesByFile, filesWithTitleFilter };
    return cachedFilter;
  } catch (err) {
    console.warn(
      `[TAP] Failed to read TAP_TEST_FILTER at ${filterPath}: ${(err as Error).message} — disabling per-test filter`,
    );
    cachedFilter = null;
    return cachedFilter;
  }
}

/**
 * Compute the spec-file path forms that should be looked up in the manifest.
 * The manifest may store paths rooted at the repo root (e.g.
 * `src/tests/login.spec.ts`) OR rooted at `testDir` (e.g. `login.spec.ts`),
 * so we try both and return whichever matches first.
 */
function candidatePaths(testInfo: TestInfo): string[] {
  const absolute = testInfo.file;
  const candidates = new Set<string>();

  // 1. Path relative to the Playwright config root (typically the repo root).
  try {
    const configRoot = (testInfo.project as { testDir?: string }).testDir
      ? path.resolve((testInfo.project as { testDir: string }).testDir, '..')
      : process.cwd();
    candidates.add(normaliseToPosix(path.relative(configRoot, absolute)));
  } catch {
    /* ignore */
  }

  // 2. Path relative to the project's testDir.
  try {
    const testDir = (testInfo.project as { testDir?: string }).testDir;
    if (testDir) {
      candidates.add(normaliseToPosix(path.relative(testDir, absolute)));
    }
  } catch {
    /* ignore */
  }

  // 3. Path relative to cwd.
  candidates.add(normaliseToPosix(path.relative(process.cwd(), absolute)));

  // 4. Absolute path as a last resort (manifests should never use absolutes,
  //    but be defensive).
  candidates.add(normaliseToPosix(absolute));

  return [...candidates].filter((p) => p.length > 0);
}

/**
 * Skip the current test when the TAP manifest is active and this test isn't
 * in it. Call from `test.beforeEach`:
 *
 *   test.beforeEach(({}, testInfo) => skipIfNotInTapFilter(testInfo));
 *
 * Behaviour:
 *   - No manifest loaded (env var unset) → no-op, every test runs.
 *   - Manifest active and this spec file isn't in it → skip. (This is also
 *     handled by `testIgnore` at the file level; the duplicate check here
 *     is defensive.)
 *   - Manifest active, file is in it, and at least one manifest entry for
 *     this file carries a title → skip tests whose titles aren't listed.
 *   - Manifest active, file is in it, and NO entries for this file carry
 *     titles → run every test in the file.
 */
export function skipIfNotInTapFilter(testInfo: TestInfo): void {
  const filter = loadFilter();
  if (!filter) return;

  const candidates = candidatePaths(testInfo);

  // Locate which form of the file path matches the manifest, if any.
  let matchedFile: string | null = null;
  for (const candidate of candidates) {
    if (filter.files.has(candidate)) {
      matchedFile = candidate;
      break;
    }
  }

  if (!matchedFile) {
    testInfo.skip(true, `[TAP] ${testInfo.file} is not in the TAP execution manifest`);
    return;
  }

  // File is in the manifest but no titles → run every test in the file.
  if (!filter.filesWithTitleFilter.has(matchedFile)) return;

  const allowedTitles = filter.titlesByFile.get(matchedFile);
  if (!allowedTitles || allowedTitles.size === 0) return;

  if (!allowedTitles.has(testInfo.title)) {
    testInfo.skip(
      true,
      `[TAP] Test "${testInfo.title}" is not in the TAP execution manifest for ${matchedFile}`,
    );
  }
}

/**
 * Reset the cached manifest. Exposed for unit tests that need to reload
 * after mutating the env var or manifest file; application code should not
 * call this.
 */
export function _resetTapFilterCacheForTests(): void {
  cachedFilter = undefined;
}
